version: '3'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginxproxymanager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${HOME_DIR}/data:/data
      - ${HOME_DIR}/letsencrypt:/etc/letsencrypt