version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: focalboard
    depends_on:
      - focalboard-db
    ports:
      - '${PORTS}:8000'
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
    volumes:
      - "${HOME_DIR}/config.json:/opt/focalboard/config.json"
      - ${HOME_DIR}/fbdata:/opt/focalboard/data
    restart: always
    networks:
      - proxy
      - default

#  proxy:
#    image: jwilder/nginx-proxy:latest
#    container_name: focalboard-proxy
#    restart: always
#    ports:
#      - 80:80
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    networks:
#      - proxy

  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - ${HOME_DIR}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}

volumes:
  fbdata:
  pgdata:

#networks:
#  proxy: