version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /home/docker/pingvin-share/data:/opt/app/backend/data
    networks:
      - nginxproxymanager_default


networks:
    nginxproxymanager_default:
        external: true