version: '3.6'

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /path/to/host/data:/app/data
    ports:
      - 50050:5005
    environment:
      - PASSWORD=password
    restart: unless-stopped
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true