version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    networks:
    - nginxproxymanager_default
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /home/docker/homebox-data:/data/
    ports:
      - 7745:7745

volumes:
   homebox-data:
     driver: local

networks:
  nginxproxymanager_default:
    external: true