version: '3.5'
services:
  jellyfin:
    #image: jellyfin/jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    user: root
    #network_mode: 'host'
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/data/tvshows:/data/tvshows
      - ${PWD}/data/movies:/data/movies
    restart: 'unless-stopped'
    networks:
      - default_network
    ports:
      - "${PORTS}:8096"
      #- "8921:8920" # Optional
    environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
networks:
    default_network:
        external: true