version: '3.3'
services:
    portainer-ce:
        image: 'portainer/portainer-ce:latest'
        container_name: portainer
        restart: unless-stopped
        networks:
            - nginxproxymanager_default
        ports:
            - '${PORTS}:9000'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${HOME_DIR}/data:/data

networks:
    nginxproxymanager_default:
        external: true