version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    ports:
      - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "mynewpassword"
    volumes:
      - /home/docker/traggo/data:/opt/traggo/data
    restart: unless-stopped
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true