version: "2.2"
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - SECRET_PATH=/nuevocs #optional
    volumes:
      - /home/docker/pwndrop:/config
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - nginxproxymanager_default
networks:
  nginxproxymanager_default:
    external: true